apiVersion: v1
kind: Service
metadata:
  name: auction-service
  namespace: web-node
spec:
  selector:
    app: webauction
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30444